services:
  db:
    image: postgres:17
    container_name: postgres
    environment:
        POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
